  name: Rust CI

  on: [push, pull_request]

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Installer Rust
          run: rustup update stable
        - name: Compiler
          run: cargo build --verbose
        - name: Tester
          run: cargo test
